config/routes.rb
Rails.application.routes.draw do
  resources :quotes, :only => [:show, :index]
  resources :posts, :only => [:show, :index]
  get 'static/authors'
  get 'static/home'

  root "static#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content

  has_rich_text :content
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :topic)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:content)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @quote = Quote.order(Arel.sql('RAND()')).first
  end

  def authors; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/layouts/action_text/contents/_content.html.haml
.trix-content
  = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zārku Pasaule
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    - begin
      = stylesheet_link_tag "application", params[:controller], "data-turbo-track": "reload", extname: ".css.css"
    - rescue
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = render 'shared/nav'
    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.rich_text_area :content
  .field
    = f.label :topic
    = f.select :topic, [["Ziņās", 0], ["Reklāma", 1], ["Sludinājums", 2]]
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%main
  - @posts.each do |post|
    %section.coffin
      .coffin_top
        %h2=link_to post.title, post
      .coffin_bottom
        .text
          - plain_text = post.content.body.to_plain_text
          - cutoff = 500
          - if  plain_text.length < cutoff
            =post.content
          - else
            - plain_text = plain_text[0, cutoff] + '...'
            - content = ActionText::Content.new(plain_text)
            = content


-# = link_to 'New Post', new_post_path, class: 'button'

app/views/posts/new.html.haml
%h1 New post

= render 'form'
%br
= link_to 'Atpakaļ', posts_path, class: "button"

app/views/posts/show.html.haml
%p#notice= notice

%main.show
  %h2.showh2=@post.title
  =@post.content

  .bottom_line
    = link_to 'Atpakaļ', posts_path, class: 'button'
    -# = link_to 'Edit', edit_post_path(@post), class: 'button'
    -# = button_to 'Delete', @post, method: :delete, class: 'button', data: {confirm: "Are you sure?"}

app/views/quotes/_form.html.haml
= form_for @quote do |f|
  - if @quote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@quote.errors.count, "error")} prohibited this quote from being saved:"
      %ul
        - @quote.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/quotes/edit.html.haml
%h1 Editing quote

= render 'form'

= link_to 'Show', @quote
\|
= link_to 'Back', quotes_path

app/views/quotes/index.html.haml
%main
  - @quotes.each do |quote|
    .tomb_stone
      %p= quote.content


-# = link_to 'New Quote', new_quote_path, class: 'button'

app/views/quotes/new.html.haml
%h1 New quote

= render 'form'

= link_to 'Back', quotes_path

app/views/quotes/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @quote.content

= link_to 'Edit', edit_quote_path(@quote)
\|
= link_to 'Back', quotes_path

app/views/shared/_nav.html.haml
%nav
  =link_to 'Zārku Pasaule', root_url
  .tabs
    %li=link_to 'Raksti', posts_url
    %li=link_to 'Citāti', quotes_url
    %li=link_to 'Redakcija', controller: :static, action: :authors